In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
##Standardisation
df=pd.read_csv('Social_Network_Ads.csv')

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df.sample(5)

     Age  EstimatedSalary  Purchased
122   40            75000          0
373   59           130000          1
331   48           119000          1
231   39            42000          0
96    35            25000          0

In [ ]:

#Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('Purchased',axis=1),df['Purchased'],test_size=0.3,random_state=0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(280, 2)
(120, 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train_scaled=sc.transform(X_train)
X_test_scaled=sc.transform(X_test)

In [ ]:
sc.mean_

array([3.78642857e+01, 6.98071429e+04])

In [ ]:
X_train

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[280 rows x 2 columns]

In [ ]:
X_train_scaled

array([[-1.1631724 , -1.5849703 ],
       [ 2.17018137,  0.93098672],
       [ 0.0133054 ,  1.22017719],
       [ 0.20938504,  1.07558195],
       [ 0.40546467, -0.48604654],
       [-0.28081405, -0.31253226],
       [ 0.99370357, -0.8330751 ],
       [ 0.99370357,  1.8563962 ],
       [ 0.0133054 ,  1.24909623],
       [-0.86905295,  2.26126285],
       [-1.1631724 , -1.5849703 ],
       [ 2.17018137, -0.80415605],
       [-1.35925203, -1.46929411],
       [ 0.40546467,  2.2901819 ],
       [ 0.79762394,  0.75747245],
       [-0.96709276, -0.31253226],
       [ 0.11134522,  0.75747245],
       [-0.96709276,  0.55503912],
       [ 0.30742485,  0.06341534],
       [ 0.69958412, -1.26686079],
       [-0.47689368, -0.0233418 ],
       [-1.7514113 ,  0.3526058 ],
       [-0.67297331,  0.12125343],
       [ 0.40546467,  0.29476771],
       [-0.28081405,  0.06341534],
       [-0.47689368,  2.2901819 ],
       [ 0.20938504,  0.03449629],
       [ 1.28782302,  2.20342476],
       [ 0.79762394,  0.26584866],
       [-0.28081405,  0.15017248],
       [ 0.0133054 , -0.54388463],
       [-0.18277423,  0.15017248],
       [-0.08473441,  0.23692961],
       [ 0.0133054 , -0.25469417],
       [ 2.17018137,  1.104501  ],
       [-1.7514113 ,  0.3526058 ],
       [ 1.87606192,  0.12125343],
       [ 0.40546467, -0.13901799],
       [-1.1631724 ,  0.29476771],
       [ 0.79762394,  1.36477242],
       [-0.28081405, -0.25469417],
       [-1.65337148, -0.05226085],
       [-0.96709276, -0.74631796],
       [ 0.30742485,  0.49720103],
       [-0.08473441, -1.06442747],
       [-1.06513258,  0.58395817],
       [ 0.11134522, -0.80415605],
       [-0.96709276,  1.53828669],
       [-0.67297331,  1.39369146],
       [-1.26121221,  0.49720103],
       [-0.28081405,  0.03449629],
       [-0.08473441,  0.00557724],
       [-0.28081405, -0.89091319],
       [ 0.89566375, -1.35361793],
       [-0.28081405,  2.2323438 ],
       [ 0.99370357,  1.97207239],
       [-1.1631724 ,  0.46828198],
       [-1.26121221,  0.26584866],
       [ 1.38586284,  1.97207239],
       [ 1.28782302, -1.35361793],
       [-0.28081405, -0.28361322],
       [-0.47689368,  1.24909623],
       [-0.77101313,  1.07558195],
       [ 0.99370357, -1.06442747],
       [ 0.30742485,  0.29476771],
       [ 0.99370357,  0.75747245],
       [-0.67297331, -1.49821316],
       [-0.67297331,  0.03449629],
       [ 0.50350449,  1.71180097],
       [ 2.07214155,  0.17909152],
       [-1.94749093, -0.74631796],
       [-0.18277423,  1.39369146],
       [ 0.40546467,  0.58395817],
       [ 0.89566375, -1.1511846 ],
       [-1.1631724 , -0.775237  ],
       [ 0.20938504,  0.23692961],
       [ 0.79762394, -0.31253226],
       [ 2.07214155, -0.80415605],
       [ 0.79762394,  0.12125343],
       [-0.28081405,  0.61287722],
       [-0.96709276, -0.31253226],
       [ 0.20938504, -0.37037036],
       [ 2.07214155,  2.11666762],
       [ 1.87606192, -1.26686079],
       [ 1.38586284, -0.91983223],
       [ 0.89566375,  1.24909623],
       [ 1.48390265,  2.11666762],
       [-0.28081405, -1.23794174],
       [ 1.97410174,  0.90206768],
       [ 0.69958412, -0.71739891],
       [-1.45729185,  0.3526058 ],
       [ 0.79762394, -1.35361793],
       [ 0.40546467, -0.13901799],
       [-0.96709276,  0.41044389],
       [ 0.0133054 , -0.31253226],
       [-1.1631724 ,  0.41044389],
       [-0.86905295, -1.2090227 ],
       [-0.08473441,  0.03449629],
       [-1.55533166, -0.42820845],
       [ 0.99370357, -1.00658937],
       [ 1.09174339, -1.2090227 ],
       [ 0.0133054 , -0.13901799],
       [-1.06513258, -1.52713221],
       [ 0.79762394, -1.2090227 ],
       [ 0.99370357,  2.05882953],
       [-1.1631724 , -1.52713221],
       [-0.28081405,  0.78639149],
       [ 0.11134522, -0.31253226],
       [-1.35925203, -1.23794174],
       [-0.5749335 , -1.49821316],
       [ 0.79762394,  0.52612008],
       [-0.28081405, -0.34145131],
       [ 1.7780221 , -0.28361322],
       [ 0.89566375, -1.03550842],
       [ 0.20938504,  0.06341534],
       [-0.5749335 ,  0.87314863],
       [-1.84945111, -1.41145602],
       [-1.26121221,  0.58395817],
       [-0.28081405,  0.52612008],
       [-0.96709276, -1.09334651],
       [ 1.1897832 , -1.44037507],
       [ 0.20938504, -0.31253226],
       [ 1.1897832 , -0.74631796],
       [-0.28081405,  0.06341534],
       [ 0.20938504,  2.08774857],
       [ 0.79762394, -1.09334651],
       [ 0.11134522,  0.03449629],
       [-1.7514113 ,  0.12125343],
       [-0.86905295,  0.15017248],
       [-0.67297331,  0.17909152],
       [ 0.89566375, -1.29577984],
       [ 0.20938504, -0.25469417],
       [-0.37885386,  1.22017719],
       [ 0.0133054 ,  0.29476771],
       [ 0.40546467,  0.15017248],
       [ 0.89566375, -0.65956082],
       [ 0.11134522,  0.15017248],
       [-1.84945111, -1.29577984],
       [-0.08473441,  0.29476771],
       [-0.18277423, -0.28361322],
       [ 0.30742485, -0.51496559],
       [-0.18277423,  1.59612479],
       [ 0.99370357, -1.18010365],
       [-0.18277423,  1.62504383],
       [ 1.28782302,  1.8563962 ],
       [-1.06513258, -0.37037036],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522, -0.25469417],
       [-1.55533166, -1.23794174],
       [-0.47689368, -0.28361322],
       [ 0.99370357,  0.12125343],
       [ 1.97410174, -1.35361793],
       [ 1.48390265,  0.06341534],
       [-0.5749335 ,  1.36477242],
       [ 1.58194247,  0.00557724],
       [-0.77101313,  0.29476771],
       [ 1.97410174,  0.7285534 ],
       [-1.1631724 , -0.51496559],
       [ 0.69958412,  0.26584866],
       [-1.35925203, -0.42820845],
       [ 0.20938504,  0.15017248],
       [-0.47689368, -1.2090227 ],
       [ 0.6015443 ,  2.00099143],
       [-1.55533166, -1.49821316],
       [-0.47689368, -0.54388463],
       [ 0.50350449,  1.82747716],
       [-1.35925203, -1.09334651],
       [ 0.79762394, -1.38253697],
       [-0.28081405, -0.42820845],
       [ 1.58194247,  0.98882482],
       [ 0.99370357,  1.42261051],
       [-0.28081405, -0.48604654],
       [-0.08473441,  2.14558666],
       [-1.45729185, -0.11009894],
       [-0.08473441,  1.94315334],
       [-0.67297331, -0.34145131],
       [-0.47689368, -0.8330751 ],
       [ 0.69958412, -1.38253697],
       [-0.77101313, -1.5849703 ],
       [-1.84945111, -1.46929411],
       [ 1.09174339,  0.12125343],
       [ 0.11134522,  1.50936765],
       [-0.28081405,  0.09233438],
       [ 0.11134522,  0.03449629],
       [-1.35925203, -1.35361793],
       [ 0.30742485,  0.06341534],
       [-0.86905295,  0.38152485],
       [ 1.58194247, -1.26686079],
       [-0.28081405, -0.74631796],
       [-0.08473441,  0.15017248],
       [-0.86905295, -0.65956082],
       [-0.67297331, -0.05226085],
       [ 0.40546467, -0.45712749],
       [-0.77101313,  1.88531525],
       [ 1.38586284,  1.27801528],
       [ 1.1897832 , -0.97767033],
       [ 1.7780221 ,  1.82747716],
       [-0.86905295, -0.25469417],
       [-0.77101313,  0.55503912],
       [-1.1631724 , -1.55605125],
       [-0.47689368, -1.12226556],
       [ 0.30742485,  0.06341534],
       [-0.18277423, -1.06442747],
       [ 1.67998229,  1.59612479],
       [ 0.99370357,  1.76963906],
       [ 0.30742485,  0.03449629],
       [-0.77101313, -0.22577513],
       [-0.08473441,  0.06341534],
       [ 0.30742485, -0.19685608],
       [ 1.97410174, -0.65956082],
       [-0.77101313,  1.33585337],
       [-1.7514113 , -0.60172273],
       [-0.08473441,  0.12125343],
       [ 0.30742485, -0.31253226],
       [ 1.09174339,  0.55503912],
       [-0.96709276,  0.26584866],
       [ 1.48390265,  0.3526058 ],
       [ 0.20938504, -0.37037036],
       [ 2.17018137, -1.03550842],
       [-0.28081405,  1.104501  ],
       [-1.65337148,  0.06341534],
       [ 0.0133054 ,  0.03449629],
       [ 0.11134522,  1.04666291],
       [-0.08473441, -0.37037036],
       [-1.1631724 ,  0.06341534],
       [-0.28081405, -1.35361793],
       [ 1.58194247,  1.104501  ],
       [-0.77101313, -1.52713221],
       [ 0.11134522,  1.8563962 ],
       [-0.86905295, -0.775237  ],
       [-0.47689368, -0.775237  ],
       [-0.28081405, -0.91983223],
       [ 0.30742485, -0.71739891],
       [ 0.30742485,  0.06341534],
       [ 0.11134522,  1.8563962 ],
       [-1.06513258,  1.94315334],
       [-1.65337148, -1.55605125],
       [-1.1631724 , -1.09334651],
       [-0.67297331, -0.11009894],
       [ 0.11134522,  0.09233438],
       [ 0.30742485,  0.26584866],
       [ 0.89566375, -0.57280368],
       [ 0.30742485, -1.1511846 ],
       [-0.08473441,  0.67071531],
       [ 2.17018137, -0.68847986],
       [-1.26121221, -1.38253697],
       [-0.96709276, -0.94875128],
       [ 0.0133054 , -0.42820845],
       [-0.18277423, -0.45712749],
       [-1.7514113 , -0.97767033],
       [ 1.7780221 ,  0.98882482],
       [ 0.20938504, -0.37037036],
       [ 0.40546467,  1.104501  ],
       [-1.7514113 , -1.35361793],
       [ 0.20938504, -0.13901799],
       [ 0.89566375, -1.44037507],
       [-1.94749093,  0.46828198],
       [-0.28081405,  0.26584866],
       [ 1.87606192, -1.06442747],
       [-0.37885386,  0.06341534],
       [ 1.09174339, -0.89091319],
       [-1.06513258, -1.12226556],
       [-1.84945111,  0.00557724],
       [ 0.11134522,  0.26584866],
       [-1.1631724 ,  0.32368675],
       [-1.26121221,  0.29476771],
       [-0.96709276,  0.43936294],
       [ 1.67998229, -0.89091319],
       [ 1.1897832 ,  0.52612008],
       [ 1.09174339,  0.52612008],
       [ 1.38586284,  2.31910094],
       [-0.28081405, -0.13901799],
       [ 0.40546467, -0.45712749],
       [-0.37885386, -0.775237  ],
       [-0.08473441, -0.51496559],
       [ 0.99370357, -1.1511846 ],
       [-0.86905295, -0.775237  ],
       [-0.18277423, -0.51496559],
       [-1.06513258, -0.45712749],
       [-1.1631724 ,  1.39369146]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns)

In [ ]:
X_train_scaled

          Age  EstimatedSalary
0   -1.163172        -1.584970
1    2.170181         0.930987
2    0.013305         1.220177
3    0.209385         1.075582
4    0.405465        -0.486047
..        ...              ...
275  0.993704        -1.151185
276 -0.869053        -0.775237
277 -0.182774        -0.514966
278 -1.065133        -0.457127
279 -1.163172         1.393691

[280 rows x 2 columns]

In [ ]:
np.round(X_train.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [ ]:
np.round(X_train_scaled.describe(),1)

         Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3

In [2]:
##Normalization
df1=pd.read_csv('wine_data.csv',header=None,usecols=[0,1,2])
df1.columns=['Class label','Alcohol','Malic acid']

In [3]:
df1.sample(10)

     Class label  Alcohol  Malic acid
127            2    11.79        2.13
35             1    13.48        1.81
148            3    13.32        3.24
42             1    13.88        1.89
108            2    12.22        1.29
6              1    14.39        1.87
126            2    12.43        1.53
21             1    12.93        3.80
172            3    14.16        2.51
72             2    13.49        1.66

In [5]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df1.drop('Class label',axis=1),
                                          df1['Class label'],test_size=0.2,random_state=0)

In [6]:
print(X_train.shape)

(142, 2)

In [7]:
print(X_test.shape)

(36, 2)

In [9]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms.fit(X_train)
X_train_norm=mms.transform(X_train)
X_test_norm=mms.transform(X_test)

In [10]:
X_train

     Alcohol  Malic acid
161    13.69        3.26
92     12.69        1.53
94     11.62        1.99
174    13.40        3.91
24     13.50        1.81
..       ...         ...
103    11.82        1.72
67     12.37        1.17
117    12.42        1.61
47     13.90        1.68
172    14.16        2.51

[142 rows x 2 columns]

In [12]:
X_train_norm=pd.DataFrame(X_train_norm,columns=X_train.columns)

In [13]:
X_train_norm

      Alcohol  Malic acid
0    0.715054    0.513238
1    0.446237    0.160896
2    0.158602    0.254582
3    0.637097    0.645621
4    0.663978    0.217923
..        ...         ...
137  0.212366    0.199593
138  0.360215    0.087576
139  0.373656    0.177189
140  0.771505    0.191446
141  0.841398    0.360489

[142 rows x 2 columns]

In [14]:
X_test_norm=pd.DataFrame(X_test_norm,columns=X_test.columns)

In [15]:
X_test_norm

     Alcohol  Malic acid
0   0.728495    0.189409
1   0.473118    0.393075
2   0.360215    0.079430
3   0.680108    0.201629
4   0.543011    1.030550
5   0.142473    0.266802
6   0.814516    0.287169
7   0.357527    0.629328
8   0.327957    0.201629
9   0.282258    0.221996
10  0.626344    0.370672
11  0.766129    0.875764
12  0.852151    0.207739
13  0.360215    0.067210
14  0.685484    0.374745
15  0.260753    0.036660
16  0.733871    0.160896
17  0.849462    0.173116
18  0.432796    0.126273
19  0.752688    0.185336
20  0.559140    0.054990
21  0.543011    0.185336
22  0.594086    0.376782
23  0.397849    0.201629
24  0.349462    0.073320
25  0.400538    0.344196
26  0.376344    0.160896
27  0.303763    0.177189
28  0.196237    0.395112
29  0.739247    0.411405
30  0.634409    0.209776
31  0.857527    0.195519
32  0.271505    0.725051
33  0.854839    0.672098
34  1.021505    0.183299
35  0.543011    0.209776

In [17]:
np.round(X_train.describe(),1)

       Alcohol  Malic acid
count    142.0       142.0
mean      13.0         2.4
std        0.8         1.1
min       11.0         0.7
25%       12.3         1.6
50%       13.0         1.9
75%       13.6         3.2
max       14.8         5.6

In [18]:
np.round(X_train_norm.describe(),1)

       Alcohol  Malic acid
count    142.0       142.0
mean       0.5         0.3
std        0.2         0.2
min        0.0         0.0
25%        0.4         0.2
50%        0.5         0.2
75%        0.7         0.5
max        1.0         1.0